# Generated by Django 5.2.7 on 2025-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'permissions': [('can_view', 'Can view'), ('can_create', 'Can create'), ('can_edit', 'Can edit'), ('can_delete', 'Can delete')],
            },
        ),
    ]
