# Generated by Django 5.2.7 on 2025-11-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'permissions': [('can_view', 'Can view the cars'), ('can_create', 'Can create the cars'), ('can_edit', 'Can edit the cars'), ('can_delete', 'Can delete the cars')], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
