# Generated by Django 5.2.7 on 2025-11-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_cars_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'permissions': [('can_view_cars', 'Can view the cars'), ('can_create_cars', 'Can create the cars'), ('can_edit_cars', 'Can edit the cars'), ('can_delete_cars', 'Can delete the cars')], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
