# Generated by Django 5.2.5 on 2025-11-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_change_book', 'Can change book'), ('can_add_book', 'Can add book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
